### ISSUE TITLE
Usability issue

### ISSUE THREAD

**Issue by henlejeremias** [helotpl/cliptable#1]
I cannot find a way to get the app to work. It is especially unclear to me how a source file (Numbers) is selected and where the resulting LaTeX code is outputted. Thank you in advance for the feedback.

**Comment by helotpl** [comment]
Application works on tables that are in clipboard (when numbers send table to clipboard it stores it in several formats such as plain text, html, rtf and some internal formats). When you select html/numbers it will look for html table in clipboard, covert it to desired output and store back to clipboard for you to paste it to LaTeX editor you are using.

Shorter version: select table in numbers, cmd+C, click convert > in clip table, and paste into LaTeX editor.

Please note that app looks for format inside cells of table. So so it will mark bold text (even if it is part of a cell), and convert italic font into equation ($ ... $). Please give it a try.

Unfortunately I'm to occupied with my research work at this moment, so I don't have time to give this app some love in terms of proper documentation. I find it useful in my work, and hope it will be useful to you.

Thanks for contacting me here, I hope my reply will help you.
